### ISSUE TITLE
Checkpoints and saving

### ISSUE THREAD

**Issue by THEpWn3R-o** [axolotl-ai-cloud/axolotl#208]
Hello! This isn't an issue, I was just wondering if there is a feature or option to save checkpoints of the model during training.

**Comment by NanoCode012** [comment]
It should for full weights!

Do you mean for PEFT? I asked them here as they just changed their saving mechanism. https://github.com/huggingface/peft/issues/574

**Comment by THEpWn3R-o** [comment]
Sorry, I'm new to the whole ai world and I'm trying to get my bearings still, I'm an undergrad going in for ai.  Bear with me please lol

How would I take checkpoints of full weight? I also know that axolotl uses peft but I'm not entirely sure what it is at the moment

**Comment by NanoCode012** [comment]
Sure! No worries. We all start somewhere!

PEFT training means that you fine-tune a model using an adapter (LORA / qlora). It would freeze the base model's layer then train some newly added layers. As of now, only the adapter is changed due to an update in the upstream repo.

Fullweights fine-tuning means that you are fine-tuning the base model itself. This is more costly and slow. The weights should be saved at each epoch.

To know which you are using in axolotl, you can check the value of `adapter: ` in the config.yaml.
If you're using a pre-made example config, the file name might also indicate it.

**Comment by NanoCode012** [comment]
Please follow #198 if you have issue with PEFT resume from training.

**Comment by THEpWn3R-o** [comment]
Awesome, thank you so much!
