### ISSUE TITLE
Should we use master branch or stable version?

### ISSUE THREAD

**Issue by fzyzcjy** [axolotl-ai-cloud/axolotl#2144]
### What piece of documentation is affected?

Hi thanks for the library! Usually it is suggested to use stable version of a package (e.g. "release v0.5.2"), but it seems the README here uses the master branch, and the docker image is also mainly about latest master. Therefore, I wonder whether it is OK to use the master branch? i.e. will it be too unstable?

### What part(s) of the article would you like to see updated?

(see above)

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by winglian** [comment]
here's the diff of main vs the last release. There are mostly a lot of test fixes and updating to use some of the more recent upstream dependencies. We should be cutting a new release on Monday after I get some more testing updates done this weekend. Depending on what features you need most of the changes since 0.5.2 are likely to not affect you.

* release 0.5.2 by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2086
* use pep440 instead of semver by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2088
* Fix duplication of plugin callbacks by @chiragjn in https://github.com/axolotl-ai-cloud/axolotl/pull/2090
* fix inference when no chat_template is set, fix unsloth dora check by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2092
* Enable Ascend NPU support by @MengqingCao in https://github.com/axolotl-ai-cloud/axolotl/pull/1758
* Bump liger-kernel requirements to 0.4.2 by @bursteratom in https://github.com/axolotl-ai-cloud/axolotl/pull/2096
* fix None-type not iterable error when deepspeed is left blank w/ use_… by @bursteratom in https://github.com/axolotl-ai-cloud/axolotl/pull/2087
* actions/create-release is unmaintained, and doesn't create proper release notes by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2098
* updated colab notebook by @bursteratom in https://github.com/axolotl-ai-cloud/axolotl/pull/2074
* `.gitignore` additions by @tmm1 in https://github.com/axolotl-ai-cloud/axolotl/pull/349
* move shared pytest conftest to top level tests by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2099
* add finetome dataset to fixtures, check eval_loss in test by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2106
* fix: ds3 and fsdp lmbench eval by @NanoCode012 in https://github.com/axolotl-ai-cloud/axolotl/pull/2102
* support seperate lr for embeddings, similar to loraplus by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/1910
* add e2e tests for Unsloth qlora and test the builds by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2093
* Add Exact Deduplication Feature to Preprocessing Pipeline by @olivermolenschot in https://github.com/axolotl-ai-cloud/axolotl/pull/2072
* various tests fixes for flakey tests by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2110
* build causal_conv1d and mamba-ssm into the base image by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2113
* make the eval size smaller for the resume test by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2111
* use pytest sugar and verbose for more info during ci by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2112
* Check torch version for ADOPT optimizer + integrating new ADOPT updates by @bursteratom in https://github.com/axolotl-ai-cloud/axolotl/pull/2104
* fix(vlm): handle legacy conversation data format and check image in data by @NanoCode012 in https://github.com/axolotl-ai-cloud/axolotl/pull/2018
* Add ds model card, rebased by @bursteratom in https://github.com/axolotl-ai-cloud/axolotl/pull/2101
* fix so inference can be run against quantized models without adapters by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/1834
* fix merge conflict of duplicate max_steps in config for relora by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2116
* feat: add cut_cross_entropy by @NanoCode012 in https://github.com/axolotl-ai-cloud/axolotl/pull/2091
* fix(readme): update cuda instructions during preprocess by @NanoCode012 in https://github.com/axolotl-ai-cloud/axolotl/pull/2114
* fix optimizer reset for relora sft by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/1414
* prepare plugins needs to happen so registration can occur to build the plugin args by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2119
* add missing fixture decorator for predownload dataset by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2117
* replace tensorboard checks with helper function by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2120
* drop unnecessary BNB_CUDA_VERSION env var from docker as it just results in warnings by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2121
* update fix_untrained_tokens from unsloth with additional fixes by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2122
* cleanup the readme, add Modal as sponsor by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2130
* fix license header for fix_untrained_tokens from unsloth-zoo by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2129
* CLI Implementation with Click by @djsaunde in https://github.com/axolotl-ai-cloud/axolotl/pull/2107
* auto-versioning and adding axolotl.__version__ by @djsaunde in https://github.com/axolotl-ai-cloud/axolotl/pull/2127
* remove accidentally included symlink by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2131
* upgrade bnb 0.45.0 and peft by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2126
* Fix broken CLI; remove duplicate metadata from setup.py by @djsaunde in https://github.com/axolotl-ai-cloud/axolotl/pull/2136
* reduce test concurrency to avoid HF rate limiting, test suite parity by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2128
* Fix llama type model check by @chiragjn in https://github.com/axolotl-ai-cloud/axolotl/pull/2142
* Transformers 4.47.0 by @winglian in https://github.com/axolotl-ai-cloud/axolotl/pull/2138

**Comment by fzyzcjy** [comment]
Thank you! I am mainly wondering a general question: should we use master or stable as a routine (not specific to this release)?

**Comment by djsaunde** [comment]
@fzyzcjy IMO, most users can use the latest stable version. If you want access to bleeding-edge features as they are added, then it might make sense to check out master, but as you noted, it may be less stable.

In short, in depends on how you intend to use the package!

**Comment by fzyzcjy** [comment]
Thank you! Then I guess the doc here can be updated to clone the latest stable instead of master.

![image](https://github.com/user-attachments/assets/a3df57e1-9281-4a4f-a155-a768abf7f632)

**Comment by NanoCode012** [comment]
@fzyzcjy , thanks for that recommendation. We have an open PR to update that to install via `pip` for stable build instead #2137
