### ISSUE TITLE
Print conversation/sample if an error occurrs processing dataset

### ISSUE THREAD

**Issue by teknium1** [axolotl-ai-cloud/axolotl#593]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

When processing the dataset to tokenize, and an error occurrs for whatever reason, print to terminal the last example loaded to process, to help diagnose dataset issues.

### ✔️ Solution

print(example) 

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by NanoCode012** [comment]
Since we're calling `map` from `datasets` library and we use multiple sub-classes of `PromptTokenizingStrategy` which implement their own tokenize prompt, I'm not sure how we could add a general try catch around everything and still get the exact prompt that caused the issue.

https://github.com/OpenAccess-AI-Collective/axolotl/blob/c1382e79b6eb599f7fd210fd1a621b97bfed0d51/src/axolotl/datasets.py#L41-L45

However, I think this is a useful feature to have!
